export const POSITIONS_REQUEST = 'POSITIONS_REQUEST';
export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_COUNT_DEFAULT = 'USERS_COUNT_DEFAULT';
export const USERS_TOTAL_REQUEST = 'USERS_TOTAL_REQUEST';
export const USER_REQUEST = 'USER_REQUEST';
export const RISE_COUNT = 'RISE_COUNT';
export const TOKEN_REQUEST = 'USERS_TOTAL_REQUEST';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_UPDATE_FORM = 'SIGNUP_UPDATE_FORM';
export const SIGNUP_UPDATE_VALUE = 'SIGNUP_UPDATE_VALUE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOADING = 'LOADING';
